[tool.poetry]
name = "finalproject"
version = "0.1.0"
description = ""
authors = ["Max Bondarenko <max.zonk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"
prompt_toolkit = "3.0.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
